- name: Create lab environment
  hosts: localhost
  connection: local
  tasks:
  - name: Generate SSH keys if they do not already exist
    openssh_keypair:
      path: ~/.ssh/id_rsa
      force: False
  - name: Terraform apply
    terraform:
      lock: no
      force_init: true
      project_path: './'
      state: present
  - name: Terraform refresh
    shell: terraform refresh
  - name: Create rg file for dynamic inventory
    shell: echo { \"rg\":\"`terraform output -raw rg`\" } > rg.json
  - name: Include vars of stuff.yaml into the 'stuff' variable
    include_vars:
      file: rg.json
      name: stuff
  - name: Configure dynamic inventory file
    blockinfile:
      path: ./myazure_rm.yml
      state: present
      block: |
        include_vm_resource_groups:
        - {{ stuff["rg"] }}
  - name: Refresh inventory to ensure new instances exist in inventory
    meta: refresh_inventory
  - name: Pause 1 minute to let VMs boot up
    pause:
      minutes: 1

- name: Zypper update
  hosts: all
  remote_user: azadmin
  become: yes
  tasks:
  - name: Update
    zypper:
      name: '*'
      state: latest
    environment:
      ZYPP_LOCK_TIMEOUT: 120
  - name: Install fio 
    zypper:
      name: fio
      state: present
    environment:
      ZYPP_LOCK_TIMEOUT: 120
  - name: Copy bellwether script to node
    copy:
      src: scripts/bellwether.fio
      dest: /home/azadmin/bellwether.fio
      mode: '0600'
      owner: azadmin
      group: users

- name: Configure prometheus and node_exporter
  hosts: all
  remote_user: azadmin
  become: yes
  tasks:
  - name: Enable opensuse repo
    command: sudo zypper addrepo -G https://download.opensuse.org/repositories/openSUSE:/Backports:/SLE-15-SP2/standard/openSUSE:Backports:SLE-15-SP2.repo
    args:  
      creates: /etc/zypp/repos.d/server_monitoring.repo
  - name: Install prometheus
    zypper:
      name: golang-github-prometheus-prometheus
      state: present
  - name: Enable prometheus
    command: sudo systemctl --now enable prometheus
  - name: Start prometheus
    command: sudo systemctl start prometheus
  - name: Install exporter
    zypper:
      name: golang-github-prometheus-node_exporter
      state: present
  - name: Enable exporter
    command: sudo systemctl --now enable prometheus-node_exporter
  - name: Start exporter
    command: sudo systemctl start prometheus-node_exporter

- name: Run bellwether.fio
  become: yes
  hosts: all
  tasks:
  - name: Run fio command (Actual IO test which takes hours)
    command: fio /home/azadmin/bellwether.fio
    async: 18000
    poll: 300
    ignore_errors: yes
  - name: Pause
    ignore_errors: yes
    pause:
      minutes: 5

- name: Deallocate VM
  hosts: localhost
  connection: local
  tasks:
  - name: Deallocate azcli command
    shell: az vm deallocate -g `terraform output -raw rg` -n `terraform output -raw node_name`
