- name: Create lab environment
  hosts: localhost
  connection: local
  tasks:
  - name: Generate SSH keys if they do not already exist
    openssh_keypair:
      path: ~/.ssh/id_rsa
      force: False
      regenerate: never
  - name: Terraform apply
    terraform:
      lock: no
      force_init: true
      project_path: './'
      state: present
  - name: Terraform refresh
    shell: terraform refresh
  - name: Pause 1 minute to let VMs boot up
    pause:
      minutes: 1

- name: Upgrade all packages and install fio/bellwether script
  hosts: all
  remote_user: azadmin
  become: yes
  tasks:
  - name: Update
    apt:
      name: '*'
      state: latest
      update_cache: yes
  - name: Install fio 
    apt:
      name: fio
      state: present
  - name: Copy bellwether script to node
    copy:
      src: scripts/bellwether.fio
      dest: /home/azadmin/bellwether.fio
      mode: '0600'
      owner: azadmin
      group: users
    
- name: Run bellwether.fio
  hosts: all
  remote_user: azadmin
  become: yes
  tasks:
  - name: Run fio command (Actual IO test which takes hours)
    command: fio /home/azadmin/bellwether.fio
    async: 18000
    poll: 300
    ignore_errors: yes    
  - name: Pause
    ignore_errors: yes  
    pause:
      minutes: 5

- name: Deallocate VM
  hosts: localhost
  connection: local
  tasks:
  - name: Deallocate azcli command
    shell: az vm deallocate -g `terraform output -raw rg` -n `terraform output -raw node_name`
    
